#!/usr/bin/env bash

# Some variables...
PHP_CLI_IMAGE="ghcr.io/fusionspim/php-capsule-listener/php-cli:latest"

# Check running directory...
if [ "$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )" != "$(pwd)" ]; then
    echo "Script should be run from php-capsule-listener folder" >&2
    exit 1;
fi

# Ensure that Docker is running...
if ! docker info > /dev/null 2>&1; then
    echo "Docker is not running." >&2
    exit 1
fi

# Handle commands...
if [ $# -gt 0 ]; then
    # Initiate a Bash shell...
    if [ "$1" == "shell" ]; then
        shift 1

        docker run -it --rm --name php-capsule-listener --volume "$PWD":/var/www/vhosts/php-capsule-listener --workdir /var/www/vhosts/php-capsule-listener $PHP_CLI_IMAGE sh

    # Execute PHP CS Fixer...
    elif [ "$1" == "fix" ]; then
        docker run -it --rm --name php-capsule-listener --volume "$PWD":/var/www/vhosts/php-capsule-listener --workdir /var/www/vhosts/php-capsule-listener $PHP_CLI_IMAGE composer run fix

    # Execute PHPUnit testsuite...
    elif [ "$1" == "test" ]; then
        docker run -it --rm --name php-capsule-listener --volume "$PWD":/var/www/vhosts/php-capsule-listener --workdir /var/www/vhosts/php-capsule-listener $PHP_CLI_IMAGE composer run test

    # Proxy PHPUnit commands...
    elif [ "$1" == "phpunit" ]; then
        shift 1

        docker run -it --rm --name php-capsule-listener --volume "$PWD":/var/www/vhosts/php-capsule-listener --workdir /var/www/vhosts/php-capsule-listener $PHP_CLI_IMAGE php vendor/bin/phpunit "$@"

    # Proxy Composer commands...
    elif [ "$1" == "composer" ]; then
        shift 1

        docker run -it --rm --name php-capsule-listener --volume "$PWD":/var/www/vhosts/php-capsule-listener --workdir /var/www/vhosts/php-capsule-listener $PHP_CLI_IMAGE composer "$@"

    fi
else
    # Show command usage instructions...
    echo "       ./php-capsule-listener shell"
    echo "       ./php-capsule-listener fix"
    echo "       ./php-capsule-listener test"
    echo "       ./php-capsule-listener phpunit <command>"
    echo "       ./php-capsule-listener composer <command>"
fi
